//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessAccount
    {
        public int IdAccessAccount { get; set; }
        public string UserName { get; set; }
        public System.Guid IdEmployee { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
