//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessAccount
    {
        public int IdAccessAccount { get; set; }
        public string UserName { get; set; }
        public System.Guid IdEmployee { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
