//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid IdAddress { get; set; }
        public System.Guid IdClient { get; set; }
        public string Street { get; set; }
        public byte Number { get; set; }
        public short PostalCode { get; set; }
        public string Colony { get; set; }
        public string Status { get; set; }
        public string Reference { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
