//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid IdAddress { get; set; }
        public System.Guid IdClient { get; set; }
        public string Street { get; set; }
        public byte Number { get; set; }
        public short PostalCode { get; set; }
        public string Colony { get; set; }
        public string Status { get; set; }
        public string Reference { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
