//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReconciliation
    {
        public System.Guid IdCashReconciliation { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public decimal StartingAmount { get; set; }
        public decimal FinishingAmount { get; set; }
        public decimal SalesAmount { get; set; }
        public decimal SpendingsAmount { get; set; }
        public decimal CashDifference { get; set; }
        public string Observations { get; set; }
        public System.Guid RegisteredBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
