//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReconciliation
    {
        public System.Guid IdCashReconciliation { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public decimal StartingAmount { get; set; }
        public decimal FinishingAmount { get; set; }
        public decimal SalesAmount { get; set; }
        public decimal SpendingsAmount { get; set; }
        public decimal CashDifference { get; set; }
        public string Observations { get; set; }
        public System.Guid RegisteredBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
