//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryOrder()
        {
            this.DeliveryOrderProduct = new HashSet<DeliveryOrderProduct>();
        }
    
        public System.Guid IdDeliveryOrder { get; set; }
        public System.Guid IdClient { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total { get; set; }
        public System.Guid DeliveryDriver { get; set; }
        public string NotDeliveredReason { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryOrderProduct> DeliveryOrderProduct { get; set; }
    }
}
