//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryOrder()
        {
            this.DeliveryOrderProduct = new HashSet<DeliveryOrderProduct>();
        }
    
        public System.Guid IdDeliveryOrder { get; set; }
        public System.Guid IdClient { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total { get; set; }
        public System.Guid DeliveryDriver { get; set; }
        public string NotDeliveredReason { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryOrderProduct> DeliveryOrderProduct { get; set; }
    }
}
