//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReport
    {
        public System.Guid IdInventoryReport { get; set; }
        public System.Guid Reporter { get; set; }
        public string Observations { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
