//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItaliasPizzaDBEntities : DbContext
    {
        public ItaliasPizzaDBEntities()
            : base("name=ItaliasPizzaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessAccount> AccessAccount { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<CashReconciliation> CashReconciliation { get; set; }
        public virtual DbSet<Charge> Charge { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DeliveryOrder> DeliveryOrder { get; set; }
        public virtual DbSet<DeliveryOrderProduct> DeliveryOrderProduct { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<InventoryReport> InventoryReport { get; set; }
        public virtual DbSet<LocalOrder> LocalOrder { get; set; }
        public virtual DbSet<LocalOrderProduct> LocalOrderProduct { get; set; }
        public virtual DbSet<MeasurementUnit> MeasurementUnit { get; set; }
        public virtual DbSet<OrderedSupply> OrderedSupply { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<RecipeSupply> RecipeSupply { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierOrder> SupplierOrder { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<SupplyCategory> SupplyCategory { get; set; }
        public virtual DbSet<SupplyInventoryReport> SupplyInventoryReport { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
    }
}
