//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItaliasPizzaDBEntities : DbContext
    {
        public ItaliasPizzaDBEntities()
            : base("name=ItaliasPizzaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessAccount> AccessAccount { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<CashReconciliation> CashReconciliation { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DeliveryOrder> DeliveryOrder { get; set; }
        public virtual DbSet<DeliveryOrderProduct> DeliveryOrderProduct { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<InventoryReport> InventoryReport { get; set; }
        public virtual DbSet<LocalOrder> LocalOrder { get; set; }
        public virtual DbSet<LocalOrderProduct> LocalOrderProduct { get; set; }
        public virtual DbSet<OrderedSupply> OrderedSupply { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<RecipeSupply> RecipeSupply { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierOrder> SupplierOrder { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<SupplyInventoryReport> SupplyInventoryReport { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
    }
}
