//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalOrderProduct
    {
        public System.Guid IdLocalOrderProduct { get; set; }
        public System.Guid IdLocalOrder { get; set; }
        public System.Guid IdProduct { get; set; }
        public int Quantity { get; set; }
    
        public virtual LocalOrder LocalOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
