//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalOrderProduct
    {
        public System.Guid IdLocalOrderProduct { get; set; }
        public System.Guid IdLocalOrder { get; set; }
        public System.Guid IdProduct { get; set; }
        public int Quantity { get; set; }
    
        public virtual LocalOrder LocalOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
