//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalOrder()
        {
            this.LocalOrderProduct = new HashSet<LocalOrderProduct>();
        }
    
        public System.Guid IdLocalOrder { get; set; }
        public System.Guid Waiter { get; set; }
        public int IdOrderStatus { get; set; }
        public int Table { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalOrderProduct> LocalOrderProduct { get; set; }
    }
}
