//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedSupply
    {
        public int IdOrderedSupply { get; set; }
        public System.Guid IdSupply { get; set; }
        public System.Guid IdSupplierOrder { get; set; }
        public System.Guid OrderIdentifier { get; set; }
        public decimal Quantity { get; set; }
        public int IdMeasurementUnit { get; set; }
    
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
