//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedSupply
    {
        public System.Guid IdOrderedSupply { get; set; }
        public System.Guid IdSupply { get; set; }
        public System.Guid IdSupplierOrder { get; set; }
        public int Quantity { get; set; }
        public string MeasurementUnit { get; set; }
    
        public virtual SupplierOrder SupplierOrder { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
