//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeSupply
    {
        public System.Guid IdProductSupply { get; set; }
        public System.Guid IdRecipe { get; set; }
        public System.Guid IdSupply { get; set; }
        public decimal SupplyAmount { get; set; }
        public Nullable<long> MeasurementUnit { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
