//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrder()
        {
            this.OrderedSupply = new HashSet<OrderedSupply>();
        }
    
        public System.Guid IdSupplierOrder { get; set; }
        public System.Guid IdSupplier { get; set; }
        public System.Guid IdSupply { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public int IdOrderStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedSupply> OrderedSupply { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
