//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyInventoryReport
    {
        public System.Guid IdSupplyInventoryReport { get; set; }
        public System.Guid IdInvenroryReport { get; set; }
        public System.Guid IdSupply { get; set; }
        public string MeasurementUnit { get; set; }
        public decimal ExpectedAmount { get; set; }
        public decimal ReportedAmount { get; set; }
        public string DifferingAmountReason { get; set; }
    }
}
