//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrder()
        {
            this.OrderedSupply = new HashSet<OrderedSupply>();
        }
    
        public System.Guid IdSupplierOrder { get; set; }
        public System.Guid IdSupplier { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedSupply> OrderedSupply { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
