//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyInventoryReport
    {
        public System.Guid IdSupplyInventoryReport { get; set; }
        public System.Guid IdInvenroryReport { get; set; }
        public System.Guid IdSupply { get; set; }
        public string MeasurementUnit { get; set; }
        public decimal ExpectedAmount { get; set; }
        public decimal ReportedAmount { get; set; }
        public string DifferingAmountReason { get; set; }
    }
}
