//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid IdTransaction { get; set; }
        public int Type { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public int Description { get; set; }
        public System.Guid RegisteredBy { get; set; }
    }
}
